### ISSUE TITLE
How deploy in ubuntu?

### ISSUE THREAD

**Issue by johnfelipe** [NRCan/datahub-portal#247]
Pls share md file for this purpose

**Comment by gcerik** [comment]
sorry for the delay, I missed the notification on this issue. We do not have yet specific instructions to deploy this on Ubuntu. For Ubuntu, you would need to install SQL Server first and .net 6. Once these are installed the Offline mode should work. Let us know if you have any other questions.

**Comment by johnfelipe** [comment]
but is possible create installation markdown for any linux?

**Comment by gcerik** [comment]
no plans yet to provide linux installations instructions however feel free to open a new issue if you get any specific error message
