### ISSUE TITLE
Storage Explorer - View Storage - DataHub - Uploaded file has incorrect date

### ISSUE THREAD

**Issue by winghonghuynh** [NRCan/datahub-portal#399]
When the user clicks on the initiative and then clicks storage explorer > view storage > DataHub > Upload to upload the file, the file is successfully uploaded but the date in the 'Last Modified' column is incorrect and shows as "Mon, 01 Jan 0001 00:00:00 GMT.

**Comment by gcnabeel** [comment]
fixed with file explorer update
