### ISSUE TITLE
Storage Explorer - New Folder - Folder disappears after creation

### ISSUE THREAD

**Issue by winghonghuynh** [NRCan/datahub-portal#402]
In Dev environment:
When the user clicks on an initiative and goes to Storage Explorer > View Storage > New Folder, a new folder is created, but when the user clicks on the new folder and goes back to the previous page, the new folder that was created disappears

**Comment by gcnabeel** [comment]
Deactived the new folder for now. We need a strategy to upgrade the storage accounts to allow for this functionality.
